### ISSUE TITLE
PSKE - Cluster Provisioning (Terraform) - documentation uses deprecated provider

### ISSUE THREAD

**Issue by mmueller-rs** [plusserver/docs#158]
Hello,

In the documentation [PSKE - Cluster Provisioning (Terraform)](https://docs.plusserver.com/en/container/managed-kubernetes/documentation/clusterinteraction/terraform-cluster-provisioning/), the deprecated provider [kubectl](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) is used whose latest release is from 24.03.2022.

Therefore an alternative should be evaluated and documented.

Potential alternatives could be:
* [kubernetes](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs)
  * In my tests, deploying a Shoot-Cluster via [kubernetes_manifest](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest) with this provider failed, because of missing `list` permission for CRDs, see https://github.com/hashicorp/terraform-provider-kubernetes/issues/1665
* [kustomization](https://registry.terraform.io/providers/kbst/kustomization/0.9.6)
  * The usage of this provider is a bit complicated and requires basic Kustomization-knowledge, but in theory it works. However, I'd prefer the previous provider if possible, though I couldn't get it to run in our PSKE Cluster.

Best regards,
Max

**Comment by YorK8s** [comment]
Hello @mmueller-rs,

The kubectl provider was last updated 2 years ago but is not yet deprecated. We still have the documentation for that provider up, because since you basically can copy&paste manifests and thus it's very easy to use - especially compared to the kubernetes provider, where you have to manually create a resource definition file.

That being said, I have tried to reproduce what you've had happen.
When using our PSKE dashboard to download the kubeconfig, you get a temporary admin kubeconfig. With that you can view, delete and create whatever resources you want - including CRDs. So there should be no problem. When I did a test run with the kubernetes provider I had no issues.

Could you maybe provide me with your provider-config and resource-definition files?
What exactly were the errors you were getting?
