### ISSUE TITLE
[PSKE / Terraform] Add documentation on how to import existing clusters into Terraform

### ISSUE THREAD

**Issue by ngc4579** [plusserver/docs#68]
The documentation holds valuable [information](https://docs.plusserver.com/de/container/managed-kubernetes/documentation/clusterinteraction/terraform-cluster-provisioning/) about how to provision PSKE clusters with Terraform.

Detailed information as to how to import existing PSKE clusters would be helpful as that seems a relevant task. The following command actually works when executed with the configuration described in the article:

```
terraform import kubectl_manifest.<cluster-name> core.gardener.cloud/v1beta1//Shoot//<cluster-name>//garden-<id>
```

Yet it is unclear how to configure the cluster YAML in the resource description safely without having Terraform unwantedly / unexpectedly re-create cluster resources, especially in the case of production environments. The actual YAML of an existing cluster contains lots of administrative runtime information that seems not needed in the cluster resource YAML. Executing `terraform plan` on a downstripped version of the YAML (i.e. void of status information and automatically added labels) seems to produce unwanted effects in that Terraform tries to reconcile state against the (imported) `tfstate`.

**Comment by YorK8s** [comment]
Hey. I have looked into your problem and tried to recreate your steps. Here's what I did:

I basically did the import with the same command as you
`terraform import kubectl_manifest.<cluster-name> core.gardener.cloud/v1beta1//Shoot//<cluster-name>//garden-<id>`

Then I got the cluster manifest from the Gardener itself and copied it into my main.tf file. Keep in mind, that you may have to remove any unnecessary value key pair from the yaml like creationTimestamp, resourceVersion and the whole status section at the bottom.

Following that, I just proceeded with the normal terraform init, plan and apply procedure and it did not recreate or delete any existing cluster but rather just exhibited the expected behaviour.

If that doesn't help you, please let me know how your main.tf file looks like.

**Comment by ngc4579** [comment]
@YorK8s Thanks for getting back on this. I've commenced some tests, looking good so far. (Interestingly, the cluster YAML returned in `yaml_body` often does not even contain a `creationTimestamp` / `resourceVersion`.)

**Comment by YorK8s** [comment]
@ngc4579 Alright, great to hear. I've now also added the steps to import existing clusters into the documentation - see #102 .
Feel free to reopen or create a new issue if you have any further questions.
